language: clojure

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk11

install:
  - wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-clients_5.2.5-1_amd64.deb
  - wget https://www.foundationdb.org/downloads/5.2.5/ubuntu/installers/foundationdb-server_5.2.5-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_5.2.5-1_amd64.deb foundationdb-server_5.2.5-1_amd64.deb

script:
  - lein test
  - lein codox

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
  - $HOME/.m2

# deploy:
#   local-dir: docs
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
