language: clojure

install:
  - wget https://www.foundationdb.org/downloads/5.1.5/ubuntu/installers/foundationdb-clients_5.1.5-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_5.1.5-1_amd64.deb || true
  - wget https://www.foundationdb.org/downloads/5.1.5/bindings/java/fdb-java-5.1.5.jar
  - lein localrepo install maven_repository/fdb-java-5.1.5.jar fdb 5.1.5

script:
  - lein test
